# SwiftLint Configuration for QuickLabelTimer
# Purpose: Enforce code quality and prevent i18n regressions

# Paths to include/exclude
included:
  - QuickLabelTimer
excluded:
  - QuickLabelTimer/QuickLabelTimerTests
  - Pods
  - .build

# Opt-in rules (not enabled by default)
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - fallthrough
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - toggle_bool
  - unused_optional_binding
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - trailing_whitespace # Can be noisy
  - todo # We use TODOs intentionally

# Custom Rules for i18n
custom_rules:
  # Prevent hardcoded Korean strings (excluding comments and localized strings)
  no_hardcoded_korean:
    name: "No Hardcoded Korean Strings"
    regex: '(?<!//.*)"[^"]*[가-힣]+[^"]*"(?!.*String\(localized:)'
    match_kinds:
      - string
    message: "Hardcoded Korean string detected. Use String(localized:) instead."
    severity: error
    excluded: ".*Tests\\.swift"  # Allow in test files

  # Prevent hardcoded UI strings (common English words in UI context)
  no_hardcoded_ui_strings:
    name: "No Hardcoded UI Strings in Views"
    regex: 'Text\("[A-Z][a-z]+"\)'
    match_kinds:
      - identifier
    message: "Potential hardcoded UI string in Text(). Consider using localization keys."
    severity: warning
    excluded: ".*Preview.*|.*Example.*"  # Allow in previews

  # Ensure localization keys follow naming convention
  localization_key_format:
    name: "Localization Key Format"
    regex: 'String\(localized:\s*"(?!ui\.|a11y\.)[^%]*"'  # Exclude format strings with %
    match_kinds:
      - identifier
    message: "Localization keys should start with 'ui.' or 'a11y.' prefix."
    severity: warning

  # NEW: Catch Button with hardcoded text
  no_hardcoded_button_labels:
    name: "No Hardcoded Button Labels"
    regex: 'Button\s*\(\s*"[^"]+"\s*\)'
    match_kinds:
      - identifier
    message: "Button labels should be localized. Use Button(LocalizedStringKey)."
    severity: warning

  # NEW: Catch NavigationLink with hardcoded text
  no_hardcoded_nav_titles:
    name: "No Hardcoded NavigationLink Titles"
    regex: 'NavigationLink\s*\(\s*"[A-Za-z가-힣]'
    match_kinds:
      - identifier
    message: "NavigationLink titles should be localized."
    severity: warning

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level: 2
  statement_level: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true

force_cast: error
force_try: error

# Reporter
reporter: "xcode"
